### PR TITLE
Fix: update tests for new ephemeral timeout value

### PR DESCRIPTION
**Pull request by billypchan**
## What's new in this PR?

Fix the failed tests after Date model PR (https://github.com/wireapp/wire-ios-data-model/pull/488).

### CODE REVIEW

**Comment by mikeger** [comment]
🔥  Conflict

**Comment by daehn** [comment]
@billypchan I didn't make a new data-model release yet, will do that now.

**Comment by alexaubry** [comment]
@billypchan Do we need these fixes? I already updated `DataModel` to 110.0, and the tests were working out of the box. Did I miss something?

**Comment by billypchan** [comment]
@alexaubry The tests works again and I close this PR.

**Pull request closed without merging**
