### PR TITLE
Re-add ImageDownloadRequestStrategyTests

### PR DESCRIPTION
**Pull request by daehn**
## What's in this PR?

* Re-add `ImageDownloadRequestStrategyTests` which were deleted previously.
* Only download version < 3 asset messages in case `message.hasEncryptedAsset` evaluates to true for them.

### CODE REVIEW

**Comment by daehn** [comment]
@vytis checking locally now.

**Comment by daehn** [comment]
Something weird though, test run fine locally for me. Re-running on CI.

**Comment by mikeger** [comment]
@daehn was it removed for the reason? :)

**Comment by daehn** [comment]
@mikeger yeah maybe, but I think it would be good to have these tests around.

**Pull request merged**
